# Travis CI Configuration File

language: php

# Build matrix options
matrix:
  include:
    - php: 7.3
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 7.3
    - php: hhvm
  fast_finish: true

install:
  - composer install

script: ./build.sh
